PesawatKertas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_landingPage.urls')),
    path('board/', include('app_board.urls')),
    path('choosen_page/', include('pilihan.urls')),
]

app_board/urls.py
from django.urls import path
from app_board import views

app_name = 'app_board'

urlpatterns = [
	path('', views.board, name='board'),
]

app_landingPage/urls.py
from django.urls import path
from app_landingPage import views

app_name = 'app_landingPage'
urlpatterns = [
	path('', views.landingPage, name='landingPage'),
	path('home', views.landingPage, name='landingPage'),
	# path('signup/', views.signUp, name='sign_up'),
	# path('signin/', views.signIn, name='sign_in'),
]

pilihan/urls.py
from django.urls import path
from pilihan import views

app_name = 'pilihan'
urlpatterns = [
	path('', views.pilihan, name='choosen_page'),
]

app_board/models.py
from django.db import models

# Create your models here.

app_landingPage/models.py
from django.db import models

# Create your models here.

pilihan/models.py
from django.db import models

# Create your models here.

app_board/views.py
from django.shortcuts import render, redirect

# Create your views here.

def board(request):
	respons = {}
	return render(request, 'boardGame.html')

app_landingPage/views.py
from django.shortcuts import render, redirect

# Create your views here.

def landingPage(request):
	respons = {}
	return render(request, 'homepage.html')

pilihan/views.py
from django.shortcuts import render, redirect

# Create your views here.

def pilihan(request):
	respons = {}
	return render(request, 'choosen_page.html')

app_board/templates/boardGame.html
{% extends "base.html" %}
{% load static %}

{% block content %}
     <!-- HEADER -->
	 <header class="masthead">
        <div class="container-fluid d-flex h-100 align-items-center">
            <div class="mx-auto text-center">
				<h1  class="text-white mx-auto my-100 line1"><strong>Selamat Bermain</strong></h1>
				<button id="test">test</button>
            </div>
        </div>
    </header>
	
<body>

	<div class="hpg-content">
        <div class="row">
			<div class="col-md-12 text-center">
				<button id="tryAgain" class="btn btn-outline-primary badge-pill btn-lg text-right" style="border-color: #5F5F5F">Try Again</button>	
			</div>
	    	<div class="col-md-12">
				<p class="card-text"></p>
					<h5 class="card-title text-turn" id=TU>
						<strong>YOUR/AI TURN! WKKWKWK</strong>						
					</h5>
				<p class="card-text"></p>
					<a id="tryAgain" class="btn btn-outline-primary badge-pill btn-lg text-right" role="button" href="{% url 'pilihan:choosen_page' %}" style="border-color: #5F5F5F">Try Again</a>	
				<p class="card-text"></p>
				<div class="card border-dark mb-3 mx-auto" id="board" style="max-width: 52rem;">
					<p class="card-text"></p>
						<h5 class="card-title text-center">rencananya disini dibikin kotak boardnyawww</h5>
						
					<div class="row skeleton-horizontal" id="highest-row">
						<div class="col-1"></div>
						<div class="col-1">
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b1" style="padding: 12px 24px;"> 
							<img id="g1" src="" width="30px">
							</button>
						</div>
						<div class="column2 col-3">
							<hr class="horizontal line" >
						</div>
						<div class="col-1">
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b2" style="padding: 12px 24px;">
							<img id="g2" src="" width="30px"></button>
						</div>
						<div class="column2 col-3">
							<hr class="horizontal line">
						</div>    
						<div class="col-1">	
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b3" style="padding: 12px 24px;"> 
							<img id="g3" src="" width="30px">
							</button>
						</div>
						<div class="col-1">	</div>
					</div>

					<div class="row skeleton-vertikal" id="first-row">
						<div class="col-1">
							<hr class="vertical line">
						</div>
						<div class="column"  style="background-color: #aaa;">
							<hr class="diagonal-left line">
						</div>
						<div class="col-1">
								<hr class="vertical line">
						</div>
						<div class="column" style="background-color: #bbb;">
							<hr class="diagonal-right line">
						</div>
						<div class="col-1">
							<hr class="vertical line">
						</div>    
					</div>

					<div class="row skeleton-horizontal" id="middle-row">
						<div class="col-1"></div>
						<div class="col-1">
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b4" style="padding: 12px 24px;"> 
							<img id="g4" src="" width="30px">
							</button>
						</div>
						<div class="column2 col-3">
							<hr class="horizontal line" >
						</div>
						<div class="col-1">	
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b5" style="padding: 12px 24px;"> 
							<img id="g5" src="" width="30px">
							</button>
						</div>
						<div class="column2 col-3">
							<hr class="horizontal line">
						</div>    
						<div class="col-1">	
<!-- 							<button lass="w3-button w3-xlarge w3-white w3-border w3-round-large" id="6" style="padding: 25px 24px;"> -->
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b6" style="padding: 25px 24px;">
							<img id="g6" src="" width="30px"> 
<!-- 							<img src="/static/img/grav1.png" width="30px"> -->
							</button>
						</div>
					</div>

					<div class="row skeleton-vertikal" id="second-row">
						<div class="col-1" >
							<hr class="vertical line">
						</div>
						<div class="column"  style="background-color: #aaa;">
							<hr class="diagonal-right line">
						</div>
						<div class="col-1">
							<hr class="vertical line">
						</div>
						<div class="column" style="background-color: #bbb;">
							<hr class="diagonal-left line">
						</div>
						<div class="col-1">
							<hr class="vertical line">
						</div>    
					</div>

					<div class="row skeleton-horizontal" id="lowest-row">
						<div class="col-1"></div>
						<div class="col-1">
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b7" style="padding: 12px 24px;"> 
							<img id="g7" src="" width="30px">
							</button>
						</div>
						<div class="column2 col-3">
							<hr class="horizontal line" >
						</div>
						<div class="col-1">	
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b8" style="padding: 12px 24px;"> 
							<img id="g8" src="" width="30px">
							</button>
						</div>
						<div class="column2 col-3">
							<hr class="horizontal line">
						</div>    
						<div class="col-1">	
							<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b9" style="padding: 12px 24px;">
							<img id="g9" src="" width="30px">
							</button>
						</div>
					</div>

					<p class="card-text"></p>
				</div>
			</div>
			<div class="col-md-12">
				<div class="row right" style="padding-top: 50px;">
	        		<img src="{% static 'img/pesawat.PNG'%}">
	        	</div>
	        </div>

	    </div>
	</div>
</body>

<!-- <script>
$("button").click(function(){
	console.log("keklik3");
	$(this).toggleClass('w3-white w3-grey');
	$(this).toggleClass('btn-empty btn-fill');
	// $('button').append("<img src={% static 'img/grav1.png' %} width=30px>").button();

});	
$('#'+1).click(function(){
	console.log("keklik C1");
	$(this).toggleClass('w3-white w3-grey');
	$("#2").toggleClass('w3-white w3-grey');
	$("#4").toggleClass('w3-white w3-grey');
	$("#5").toggleClass('w3-white w3-grey');
	$(this).toggleClass('btn-empty btn-fill');

});	
</script> -->

<style>

.btn-empty{
	padding: 25px 24px;
}
.btn-fill{
	padding: 10px 14px;
}
</style>
{% endblock %}

app_landingPage/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
     <!-- HEADER -->
	 <header class="masthead">
        <div class="container-fluid d-flex h-100 align-items-center">
            <div class="mx-auto text-center">
				<h1 class="text-white mx-auto my-100 line1"><strong>Selamat Datang di Games</strong></h1>
				<h1 class="text-white mx-auto my-0"><strong>Pesawat Kertas!</strong></h1>
            </div>
        </div>
    </header>
	
<body>
	<div class="hpg-content">
	    <div class="row text-center">
	        <div class="col-md-12 text-center">
	        	<div class="col-md-8 text-center" style="padding-top: 60px; padding-right: 80px">
					<img src="{% static 'img/pesawat.PNG' %}" style="transform: rotate(10deg); ">
					<br>
				</div>
				<br>
	            <h1 class="judul-kartu">Games Apa Ini?</h1>
	        </div>
	    	<div class="col-md-12 text-center">
	            <div class="card border-dark mb-3 mx-auto" style="max-width: 35rem; padding: 35px">
	            	<p class="card-text"></p>
	            	<h5 class="card-title isi-kartu">Pesawat Kertas adalah sebuah permainan
	            						   berbentuk <i> web-based application </i>
 										   yang diadaptasi dari permainan tradisional 
 										   masyarakat Indonesia yaitu “Catur Jawa”</h5>
					<p class="card-text"></p>
	        	</div>
	    	</div>
	    </div>

	    <div class="row text-center">
		    <div class="col-md-12 text-center">
	        	<div class="col-md-12 text-center">
	        		<br>
	        		<br>
	        		<br>
	        		<br>
	        	</div>
	        </div>
	        <div class="col-md-12 text-center">
	        	<div class="col-md-11 text-right" style="padding-right: 70px">
	        			<img src="{% static 'img/pesawat.PNG' %}" style=" transform: rotate(20deg); transform: rotateY(-185deg);">
	        	</div>
	            <h1 class="judul-kartu">Bagaimana cara mainnya?</h1>
	        </div>
	    	<div class="col-md-12 text-left">
	            <div class="card border-dark mb-3 mx-auto" style="max-width: 35rem; padding: 35px ">
	            	<h5 class="card-title isi-kartu" >- Permainan dilakukan oleh 2 orang pemain.<br>
	            	- Masing-masing pemain mendapat 3 bidak.<br>
	            	- Pemain secara bergantian menggerakkan<br>
	            	&ensp; bidak.<br>
	            	- Pergerakan satu bidak yaitu 1 langkah ke<br>
	            	&ensp; posisi yang sedang tidak ditempati oleh <br>
	            	&ensp; bidak lain.<br>
    				- Pemain yang membuat garis lurus dengan 3 <br>
    				&ensp; bidak terlebih dahulu keluar sebagai <br>
    				&ensp; pemenang dan permainan berakhir.<br>
    				- Tiga spot bidak pada awal permainan tidak <br>
    				&ensp; dapat dijadikan tempat membuat garis lurus.<br></h5>
					</p>
	        	</div>
	    	</div>
	    </div>
	    <div class="row text-center">
	        <div class="col-md-12 text-center">
	        	<div class="col-md-9 text-right">
	        	<br>

	        	<img src="{% static 'img/pesawat.PNG' %}" style="transform: rotate(-20deg);">
	        	</div>
	        </div>
	    	<div class="col-md-12 text-center">
	    		<a id="masukKeGame" class="btn btn-outline-primary badge-pill btn-lg " style="padding-right: 2rem; padding-left: 2rem; color: #000000; border-color: #000000; " role="button" href="{% url 'pilihan:choosen_page' %}" style="border-color: #5F5F5F">Saya siap! </a>
				<!-- <img src="{% static 'img/pesawat.PNG' %}"> -->
	    	</div>
	    	<!-- <img src="{% static 'img/pesawat.PNG' %}"> -->
	    </div>
		<br><br><br>
	</div>
</body>
<style type="text/css">
.btn-outline-primary {
box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);	
}
.btn-outline-primary:hover {
  background-color: #B6B6B6;
  
}
.card {
	border: 3px solid rgba(0,0,0,.125);
}
</style>
<script>
	function openNav() {
	 	document.getElementById("mySidepanel").style.width = "150px";
	}

	function closeNav() {
	 	document.getElementById("mySidepanel").style.width = "0";
	}
</script>

{% endblock %}

pilihan/templates/choosen_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
     <!-- HEADER -->
	 <header class="masthead">
        <div class="container-fluid d-flex h-100 align-items-center">
            <div class="mx-auto text-center">
				<h1 id="judulUtama" class="text-white mx-auto my-100 line1"><strong>Yuk Dipilih</strong></h1>
            </div>
        </div>
    </header>

<body>
	<!-- BOARD NYA DISINI -->
	<h1 id="alertParah">Perbesar windownya lagi yaa..</h1>
	<div id="boardAkhir">
		<div class="hpg-content">
	        <div class="row">
		    	<div class="col-md-12">
					<p class="card-text"></p>
						<h5 id="turns" class="card-title text-turn"><strong></strong></h5>
					<p class="card-text"></p>
		            <div class="card border-dark mb-3 mx-auto" id="board" style="max-width: 52rem;">
						<p class="card-text"></p>
							<h5 id="petunjuk" class="card-title text-center"></h5>
							<h5 id="petunjuk2" class="card-title text-center"></h5>
							<h5 id="petunjuk3" class="card-title text-center"></h5>
							
						<div class="row skeleton-horizontal" id="highest-row">
							<div class="col-1"></div>
							<div class="col-1">
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b1" style="padding: 5px 4px;"> 
								<img id="g1" src="" width="50px">
								</button>
							</div>
							<div class="column2 col-3">
								<hr class="horizontal line" id="12">
							</div>
							<div class="col-md-auto"></div>
							<div class="col-1">
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b2" style="padding: 5px 4px;">
								<img id="g2" src="" width="50px"></button>
							</div>
							<div class="column2 col-3">
								<hr class="horizontal line" id="23">
							</div>    
							<div class="col-md-auto"></div>
							<div class="col-1">	
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b3" style="padding: 5px 4px;"> 
								<img id="g3" src="" width="50px">
								</button>
							</div>
							<div class="col-1">	</div>
						</div>

						<div class="row skeleton-vertikal" id="first-row">
							<div class="column4"></div>
							<div class="column4">
								<hr class="vertical line" id="14">
							</div>				
							<div class="col-1"></div>	
							<div class="column"  style="background-color: #aaa;">
								<hr class="diagonal-left line" id="15">
							</div>
							<div class="column4">
								<hr class="vertical line" id="25">
							</div>   
							<div class="col-1" ></div>
							<div class="column" style="background-color: #bbb;">
								<hr class="diagonal-right line" id="35">
							</div>
							<div class="column4">
								<hr class="vertical line" id="36">
							</div>    
						</div>

						<div class="row skeleton-horizontal" id="middle-row">
							<div class="col-1"></div>
							<div class="col-1">
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b4" style="padding: 5px 4px;"> 
								<img id="g4" src="" width="50px">
								</button>
							</div>
							<div class="column2 col-3">
								<hr class="horizontal line" id="45">
							</div>
							<div class="col-md-auto"></div>
							<div class="col-1">	
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b5" style="padding: 5px 4px;"> 
								<img id="g5" src="" width="50px">
								</button>
							</div>
							<div class="column2 col-3">
								<hr class="horizontal line" id="56">
							</div>    
							<div class="col-md-auto"></div>
							<div class="col-1">	

								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b6" style="padding: 5px 4px;">
								<img id="g6" src="" width="50px"> 
								</button>
							</div>
						</div>

						<div class="row skeleton-vertikal" id="second-row">
							<div class="column4"></div>
							<div class="column4" >
								<hr class="vertical line" id="47">
							</div>
							<div class="col-1" ></div>
							<div class="column"  style="background-color: #aaa;">
								<hr class="diagonal-right line" id="57">
							</div>
							<div class="column4">
								<hr class="vertical line" id="58">
							</div>
							<div class="col-1" ></div>
							<div class="column" style="background-color: #bbb;">
								<hr class="diagonal-left line" id="59">
							</div>
							<div class="column4">
								<hr class="vertical line" id="69">
							</div>    
						</div>

						<div class="row skeleton-horizontal" id="lowest-row">
							<div class="col-1"></div>
							<div class="col-1">
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b7" style="padding: 5px 4px;"> 
								<img id="g7" src="" width="50px">
								</button>
							</div>
							<div class="column2 col-3">
								<hr class="horizontal line" id="78">
							</div>
							<div class="col-md-auto"></div>
							<div class="col-1">	
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b8" style="padding: 5px 4px;"> 
								<img id="g8" src="" width="50px">
								</button>
							</div>
							<div class="column2 col-3">
								<hr class="horizontal line" id="89">
							</div>    
							<div class="col-md-auto"></div>
							<div class="col-1">	
								<button class="w3-button w3-xlarge w3-white w3-border w3-round-large" id="b9" style="padding: 5px 4px;">
								<img id="g9" src="" width="50px">
								</button>
							</div>
						</div>
						<p class="card-text"></p>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
					</div>
				</div>
				<div class="col-md-12 text-center">
					<p class="card-text"></p>
						<!-- <div style="padding-right: 2rem; padding-left: 50rem;"> -->
							<button id="tryAgain" class="btn btn-outline-primary badge-pill btn-lg" href="{% url 'pilihan:choosen_page' %}" align="right" style="border-color: #5F5F5F; padding-right: 2rem; padding-left: 2rem;">Main Lagi!</button>
						<!-- </div> -->
					<p class="card-text"></p>
				</div>
				<div class="col-md-12">
					<div class="row right" style="padding-top: 50px;">
		        		<img src="{% static 'img/pesawat.PNG'%}">
		        	</div>
		        </div>

		    </div>
		</div>
	</div>

	<!-- CHOOSEN PAGE NYA DISINI -->
	<div id="chooseAkhir">
		<div class="hpg-content" align="center-block">
			<div class="row text-center">
		        <div class="col-md-12">
		        	<div class="col-md-10 text-right" style="padding-top: 100px;">
	        				<img src="{% static 'img/pesawat.PNG'%}">
		        	</div>
			            <h1><strong>Pilih Pemain Pertama</strong></h1>
			    </div>
		        <div class="col-md-12 text-center startBy">
	            	<div class="card border-dark mb-3 mx-auto" style="max-width: 30rem;">
	            		<p class="card-text"></p>
	            			<!-- Opsi pertama -->
	            			<div class="container coba" align="center">
	            				<div></div>
	            				<div></div>
	            				<div></div>
	            				<div></div>
								<button class="btn btn-outline-dark" id="cAI" style="padding: 5px 23px; border: 1.5px solid #000000;"><Strong>AI</Strong></button>
								<button class="btn btn-outline-dark" id="cUS" style="padding: 5px 23px; border: 1.5px solid #000000;"><Strong>USER</Strong></button>
								<div></div>
								<div></div>
								<div></div>
								<div></div>
							</div>

						<br>
						<p class="card-text"></p>
	        		</div>
		    	</div>
		    </div>
		    <div class="row text-center">
		    	<div class="col-md-12 text-center">
			        <h1><strong>Pilih Level Kesulitan</strong></h1>
			    </div>
		        <div class="col-md-12 text-center difficulty">
	            	<div class="card border-dark mb-3 mx-auto" style="max-width: 30rem;">
	            		<p class="card-text"></p>
	            			<!-- Opsi Kedua -->
	            			<div class="container coba" align="center">
	            				<div></div>
	            				<div></div>
							    <button class="btn btn-outline-dark" id="cEas" style="padding: 5px 23px; border: 1.5px solid #000000;"><Strong>Mudah</Strong></button>
							    <button class="btn btn-outline-dark" id="cMed" style="padding: 5px 23px; border: 1.5px solid #000000;"><Strong>Sedang</Strong></button>
							    <button class="btn btn-outline-dark" id="cHrd" style="padding: 5px 23px; border: 1.5px solid #000000;"><Strong>Sulit</Strong></button>
							    <button class="btn btn-outline-dark" id="cSpc" style="padding: 5px 23px; border: 1.5px solid #000000;"><Strong>Spesial</Strong></button>
	            				<div></div>
	            				<div></div>
							</div>

						<br>
						<p class="card-text"></p>
	        		</div>
	    		</div>
		    </div>
		    <div class="row text-center">
		    	<div class="col-md-12 text-center">
			            <h1><strong>Pilih Gravatar</strong></h1>
			    </div>
		        <div class="col-md-12 text-center avatar">
	            	<div class="card border-dark mb-3 mx-auto" style="max-width: 30rem;">
	            		<p class="card-text"></p>
	            			<!-- Opsi ketiga -->
	            			<div class="container" align="center">
							    <button type="button" class="btn btn-outline-dark" id="cg1" style="border: 1.5px solid #000000;">
							    	<img src="{% static 'img/grav1.png' %}" width="30px">
							    </button>
							    <button type="button" class="btn btn-outline-dark" id="cg2" style="border: 1.5px solid #000000;">
							    	<img src="{% static 'img/grav2.png' %}" width="30px">
							    </button>
							    <button type="button" class="btn btn-outline-dark" id="cg3" style="border: 1.5px solid #000000;">
							    	<img src="{% static 'img/grav3.png' %}" width="30px">
							    </button>
							<!-- YANG KETIGA DIHAPUS BUAT AI -->
							    <button type="button" class="btn btn-outline-dark" id="cg4" style="border: 1.5px solid #000000;">
							    	<img src="{% static 'img/grav4.png' %}" width="30px">
							    </button>
							    <button type="button" class="btn btn-outline-dark" id="cg5" style="border: 1.5px solid #000000;">
							    	<img src="{% static 'img/grav5.png' %}" width="30px">
							    </button>
							</div>

						<br>
						<p class="card-text"></p>
	        		</div>
	    		</div>
		    </div>
		    <div class="row text-center">
				<div class="col-md-12 text-center">
					<br>
					<br>
					<a class="btn btn-outline-primary badge-pill btn-lg" style="padding-right: 2rem; padding-left: 2rem; color: #000000; border-color: #000000;" role="button" id="siapMain" style="border-color: #5F5F5F">Game dimulai!</a>
					<p id="alert">Pilih pemain pertama dulu!</p>
				</div>
		        <div class="col-md-12 text-center">
		        	<div class="col-md-9 text-left">
		        		<img src="{% static 'img/pesawat.PNG' %}" style=" transform: rotate(20deg); transform: rotateY(-185deg);">
		        	</div>
		        </div>
		    	
		    </div>
			<br><br><br>
		</div>
	</div>
</body>

<style type="text/css">
.btn-outline-primary {
box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);	
}
.btn-outline-primary:hover {
  background-color: #B6B6B6;
  
}
.card {
	border: 3px solid rgba(0,0,0,.125);
}
.active {
  background-color: #B6B6B6;
}
</style>

<script>
$(".startBy button").click(function(){
  $(".startBy button").removeClass("active");
  $(this).addClass("active");
});
$(".difficulty button").click(function(){
  $(".difficulty button").removeClass("active");
  $(this).addClass("active");
});
$(".avatar button").click(function(){
  $(".avatar button").removeClass("active");
  $(this).addClass("active");
});
  function openNav() {
	 	document.getElementById("mySidepanel").style.width = "150px";
	}

	function closeNav() {
	 	document.getElementById("mySidepanel").style.width = "0";
	}
</script>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>PesawatKertas</title>
    <link rel="icon" href="{% static 'img/logo.PNG' %}" type="image/gif">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/design.css' %}">
	<link rel="stylesheet" type="text/javascript" href="{% static 'javascr/ourJS.js' %}">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=McLaren">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
	<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
	<script src="{% static 'js/script.js' %}"></script>
</head>

<body>
	<!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="{% url 'app_landingPage:landingPage' %}"><img src="{% static 'img/logo.PNG' %}" style="width:100px;"><span class="sr-only">(current)</span></a>
	</nav>

    {% block content %}
	{% endblock %}
	
	<!-- FOOTER -->
	<footer id="myFooter">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 text-center">
					<br>
                    <img src="{% static 'img/mascot.PNG' %}" style="width:75%;">
                </div>
                <div class="col-sm-3" style="margin-left:10px; margin-right:10px;">
                    <h5>PesawatKertas</h5>
                    <ul>
                        <li class="text-justify">Sebuah permainan yang diadaptasi dari permainan tradisional masyarakat Indonesia “Catur Jawa”.</li>
                    </ul>
				</div>
                <div class="col-md-auto">
                    <h5>Proyek Akhir</h5>
                    <ul>
						<li>Multi-Agent System	</li>
                        <li>Kelompok 4</li>
						<li>Sistem Cerdas - A</li>
						<li><a href="https://gitlab.com/airship-team/pesawat-kertas.git">Link Gitlab</a></li>
                    </ul>
				</div>
				<div class="col-auto"></div>
                <div class="col-md-auto">
                    <h5>Developer</h5>
                    <ul>
                        <li>Aulia Rosyida (1706025346)</li>
                        <li>Hana Raissya (1706979266)</li>
						<li>Mutia Rahmatun Husna (1706039622)</li>
						<li>Rahmat Fadhilah (1706074902)</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>